### ISSUE TITLE
HTTP 500 when viewing composite resource

### ISSUE THREAD

**Issue by fherbert** [komodorio/komoplane#25]
Due to this assumption https://github.com/komodorio/komoplane/blob/main/pkg/backend/crossplane/crds.go#L38 that the plural form of the CRD has a "s" appended - some of ours don't. Is there a better way to get the plural form of the crd?

**Comment by undera** [comment]
Oh, well. I expected that to happen one day. 
May I ask what kind of CRD has different sort of plural? Is it XRD or something else? Out of my curiosity - how the name looks?

**Comment by fherbert** [comment]
XRD, name is aks and eks.

**Comment by undera** [comment]
I have created following XRD:
```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: eks.test.komodor.com
spec:
  connectionSecretKeys:
    - kubeconfig
  group: test.komodor.com
  names:
    kind: EKS
    plural: eks
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
```

And I see no HTTP 500 when viewing it in Komoplane. Can you provide a bit more precise description on how to reproduce it?

**Comment by fherbert** [comment]
A sample XRD looks like:
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: aks.foo.com
spec:
  group: foo.com
  names:
    kind: Aks
    listKind: AksList
    plural: aks
    singular: aks
  versions:
    - name: v1alpha1
```

I've tested by removing the + "s" and building and it no longer returns a 500.
